package:
  name: pepa
  version: "0.1.0" 
source:
    path: . 
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python>=3.0
  - numpy>=1.16
  - r-base                  # For R script support
  - r-dplyr                 # R package for organizing data
  - r-patchwork                 # R package for organizing data
  - r-ggplot2               # R package for plots
  - pip                     # Include pip for Python packages if needed
  - pip:
    - collections           # Installed by default, not always needed in pip
about:
  home: "https://github.com/yourusername/pepa_paintchr"  # Optional: URL for project home
  license: "Apache License 2.0"                          # License for your project
  summary: "Pipeline for genetic analysis using PePa PaintChr."